### ISSUE TITLE
Email credit check perpetual spinning wheel

### ISSUE THREAD

**Issue by BhargavRentala** [palmetto/Palmetto#200]
| Name | Email | Description | URL | Priority | WideSpread | StepstoReproduce |
|---|---|---|---|---|---|---|---|
| ac | andrew.catapano@palmetto.com | When issueing an EMAIL CREDIT CHECK, the homeowner receives the credit check email, but cannot proceed to input information due to perpetual spinning wheel  | https://alchemy.palmetto.com/hocreditcheck/aeG1 | High | Small Group of Users | 1) Email credit check
2) Homeowner receives email and proceeeds + accepts terms and conditions. NOTE- THE LINK FORCES BOTH FINANCIERS TO BE RUN, NEITHER CAN BE UNSELECTED 
3) Homeowner confirms they are on title and clicks yes
4) PERPETUAL SPIN - DOES NOT GET TO THE INPUT/CREDIT CHECK PART
 |

**Comment by leonardotreeline** [comment]
The state CODE for customer Andrew Catapano is MD which has a null id for sunlight_project_id and will cause that call to fail if sunlight is selected as a finance company

**Comment by BhargavRentala** [comment]
Send an email to Olaf to get the project ids

**Comment by leonardotreeline** [comment]
`State

ID

CT

0064M00000W9DOc

FL

0064M00000W9DP6

IL

0064M00000W9DPa

MA

0064M00000W9DPu

NJ

0064M00000W9DQi

NC

0064M00000W9DQx

RI

0064M00000W9DRH

SC

0064M00000W9DRb

PA

0064M00000W9VCJ

NV

0064M00000W9skL

MD

0064M00000WyM5g`
