### ISSUE TITLE
Review Net Metering Functionality to allow Utility ratio to overwrite the state ration

### ISSUE THREAD

**Issue by TyFrye** [palmetto/Palmetto#270]
Alchemy was originally designed to let a utility's net metering on/off and ratio supersede the Market-Wide Net Metering ratio and on/off setting.  
Only the state settings impact the net metering calculations in the proposal; regardless of the settings at the utility level. The utility settings do not work.
How much effort will it take to correct this action for 1 state at this time, Texas?

**Comment by kellengarnaas** [comment]
After some investigation, it appears the pieces are in place to make this functional. The current issue is that the functionality to override Net Metering is simply not existent in the current codebase, however the interface and DB is there. Adding an estimate to complete the functionality.

**Comment by BhargavRentala** [comment]
@kellengarnaas  Thanks for the estimate. Moving the card back to in-progress.

**Comment by BhargavRentala** [comment]
@TyFrye  please review this in production and close the card

**Comment by TyFrye** [comment]
Met with Kellen, and reviewed the discrepancies.

**Comment by kellengarnaas** [comment]
Changes have been reverted for previous fix due to new issue. New fix nearing completion

**Comment by TyFrye** [comment]
UAT and Production tests were satisfactory.  One bug was found, but it does not need to be fixed.  It was a known bug that was not included in the ticket. The bug only comes into play during changes to a market, there is a process work around for the bug.

The test results are noted on the following document
https://docs.google.com/spreadsheets/d/1bQIYxqObVAWs1yL7VQmr_U_fp73vQihoyp0coh8TrsU/edit?usp=sharing
