### ISSUE TITLE
Need to Open opportunity 

### ISSUE THREAD

**Issue by BhargavRentala** [palmetto/Palmetto#287]
| Name | Email | Description | URL | Priority | WideSpread | StepstoReproduce |
|---|---|---|---|---|---|---|---|
| Valentina Pena | valentinapena98@gmail.com | Please clear the error I am receiving (mentioned in slack) for this opportunity in Alchemy so that super admins may access the opp. | https://partner-admin.loanpal.com/loans/19-08-016514 | Medium | No | 1) Locate HO in Alchemy and attempt to open the opp. 
2) Receive error mentioned in slack since I cannot upload docs in ZenHub |

**Comment by BhargavRentala** [comment]
Find the customer in Alchmey, clicking on this is giving an error.
![image.png](https://images.zenhubusercontent.com/5db873bb0f0394000100138b/a7b241bd-71eb-4561-b8c0-eac6d6fd7a75)

**Comment by leonardotreeline** [comment]
@BhargavRentala found and created a PR that fixes the issue, it seems that user doesn't have a contract_loan_application and the code is assuming it will always find one. I have a little concern though but don't know if we want to/can do something about it![Screen Shot 2020-01-29 at 5.19.32 PM.png](https://images.zenhubusercontent.com/5e28ee3b8cc526a7cc897af1/5a8ea2d8-5ad1-4bab-91b0-34191825f0dd)

As you can see there is a payment option in the database that is misspelled, not sure if it's visible or not to the customer but it is definitely being used as it's also part of the code to check for it with the misspelling

**Comment by BhargavRentala** [comment]
@leonardotreeline  You will see a lot of misspelt items on the code and there is nothing to worry about. Do you know why there is nt a contract loan application for this project? and whats the fix for it? Usually, every loan project should have a contract loan application.

**Comment by leonardotreeline** [comment]
@BhargavRentala I do not know what could cause it not have a contract id, I can look into it if you would like. 
The fix I did was to check if it didn't find a contract loan application to return blank the payment status. An upper part of the same conditional sets the payment_status as blank as well if payment option is not finance.
