### ISSUE TITLE
Loan Fully Approved, No Credit Results in Alchemy

### ISSUE THREAD

**Issue by BhargavRentala** [palmetto/Palmetto#295]
| Name | Email | Description | URL | Priority | WideSpread | StepstoReproduce |
|---|---|---|---|---|---|---|---|
| AH | alyssa.haley@palmetto.com | -Customer Kathya Licea fully approved in Loanpal
-Alchemy did not indicate any credit run whatsoever
-Required super admin support to close via URL trick | https://alchemy.palmetto.com/contract/upload/documents/5wj7 | High | Yes | -Customer Kathya Licea fully approved in Loanpal
-Alchemy did not indicate any credit run whatsoever
-Required super admin support to close via URL trick |

**Comment by BhargavRentala** [comment]
Could be related to title/address change

**Comment by leonardotreeline** [comment]
This customer's opportunity has 3 contracts in the database and one of them is the loanpal approved contract but for some reason that one is not the one with the is_selected flag on, a mostly blank one for sunlight has the flag.

**Comment by leonardotreeline** [comment]
@BhargavRentala the when selecting financiers, if you don't select any of either sunlight or loanpal it will still show up as an option when submitting credit report if in that view it is selected (sunlight wasn't selected to compare but selected for credit check) it will register that contract as selected but won't really have an actual application so will be missing all the required data on that contract loan application
