### ISSUE TITLE
Credit Check Error message

### ISSUE THREAD

**Issue by BhargavRentala** [palmetto/Palmetto#323]
| Name | Email | Description | URL | Priority | WideSpread | StepstoReproduce |
|---|---|---|---|---|---|---|---|
| AH | alyssa.haley@palmetto.com | Rep was getting an error message when trying to run credit for customer. Had to manually send docs and use URL trick | https://alchemy.palmetto.com/contract/upload/documents/m2lq | Medium | No | -Rep ran simultaneous credit check
-got an error pop up message
-alchemy indicated no credit had been run
-there were 4 sunlight tiles and 4 loanpal applications, two of which had been cancelled |

**Comment by leonardotreeline** [comment]
@BhargavRentala if I wanted to run the credit check myself to see the error, which options should I choose?
