### ISSUE TITLE
Inaccessible Opportunities 

### ISSUE THREAD

**Issue by BhargavRentala** [palmetto/Palmetto#325]
| Name | Email | Description | URL | Priority | WideSpread | StepstoReproduce |
|---|---|---|---|---|---|---|---|
| Mike Noto | michael.noto@palmetto.com | There are currently 5 opportunities that are permanently stuck in the design pipeline. The "Create" button in the Action column is not available so no one can access these projects to remove or complete them. Note: All of these projects have already been duplicated and designed for the customer. | https://alchemy.palmetto.com/dashboard | Low | Small Group of Users | Unknown. The projects come into the design queue this way |

**Comment by BhargavRentala** [comment]
![image.png](https://images.zenhubusercontent.com/5db873bb0f0394000100138b/2faf58ad-d7b5-46ef-abed-05c8ca23a97a)

**Comment by leonardotreeline** [comment]
@BhargavRentala is there a user I can login with that can see this dashboard? I login with chase.holroyd@palmetto.com and apparently he is a super user so he is seeing a different dashboard

**Comment by leonardotreeline** [comment]
@BhargavRentala at first glance doesn't seem to be a difficult issue, I do need the user info to log into the design pipeline dashboard. I would say for this task right now 4hrs at most (most likely less) for the discovery in case my assumptions are incorrect

**Comment by BhargavRentala** [comment]
@leonardotreeline Login as a desinger
ictest6@infiniticreation.co.uk 
pw: 123456

**Comment by leonardotreeline** [comment]
@BhargavRentala I did a fix for the editing issue on branch LN-A101-325. When you get a chance do get us the document for the proper flow. I'll create a PR based on that. 

That fix solves most of those stuck proposal's edit but there is one with a 0 for currentProposalId which is Manrique Martinez' It seems on the flow that that id shouldn't be 0 but not sure why it is zero, maybe that is the next thing to look at.

**Comment by BhargavRentala** [comment]
@leonardotreeline  Dixie error in prod
![image.png](https://images.zenhubusercontent.com/5db873bb0f0394000100138b/6fd0d008-202f-4d1c-a73d-42c61bd18c34)

**Comment by BhargavRentala** [comment]
same error as above for Manrique

**Comment by BhargavRentala** [comment]
Closing the card @leonardotreeline
