### ISSUE TITLE
Phone number disclosure

### ISSUE THREAD

**Issue by BhargavRentala** [palmetto/Palmetto#335]
You must disclose the below Phone Disclosure in conjunction with the main credit disclosure.

_“You are providing express "written" consent for Sunlight Financial to call you (including through automated means; e.g. autodialing, text and pre-recorded messaging) via telephone, mobile device (including SMS and MMS -charges may apply), even if your telephone number is currently listed on any internal, corporate, state, federal or national Do-Not-Call (DNC) list.”_

**Comment by kellengarnaas** [comment]
Add to hyperlink PDF

**Comment by kellengarnaas** [comment]
Add to last paragraph of credit check disclosure and main disclosure:
![Screen Shot 2020-01-27 at 4.26.34 PM.png](https://images.zenhubusercontent.com/5df12c4e80dbe847857ce21b/421f8a61-0ec9-4176-a883-594dd863c1ca)

**Comment by BhargavRentala** [comment]
Looks good
