### ISSUE TITLE
Main Credit Disclosure

### ISSUE THREAD

**Issue by BhargavRentala** [palmetto/Palmetto#336]
You must display the below Main Credit Disclosure, with links, as described below. The below disclosure must be presented to the applicant before the applicant can submit any Credit information to Sunlight Financial. A positive acknowledgement will allow the applicant to proceed to submit the credit application form. This should be accomplished by disabling the ability to submit until the applicant has enabled a check-box (or equivalent)

_"I/we, the applicant and co-applicant (if applicable), have reviewed the Terms and Conditions and authorize Sunlight to submit the credit check. By clicking “Submit Application,” I/we acknowledge that I/we are providing express written consent under the Fair Credit Reporting Act for Sunlight Financial to obtain one or more consumer credit report(s) from one or more consumer reporting agencies to process my/our credit application. I/we understand that these are hard credit pulls and may affect my/our credit score.”_

**Comment by kellengarnaas** [comment]
Display on the Sunlight Terms screen between text the terms box and the accept button:
![image.png](https://images.zenhubusercontent.com/5df12c4e80dbe847857ce21b/bf4a93ba-183b-438b-9313-9cc89f62df68)

**Comment by BhargavRentala** [comment]
![image.png](https://images.zenhubusercontent.com/5db873bb0f0394000100138b/df96e77b-403f-4000-8269-a9ff4dad225b)

The co-applicant form is missing the disclosure

**Comment by BhargavRentala** [comment]
Good to deploy
