### ISSUE TITLE
 Voluntarily supply sales rep information

### ISSUE THREAD

**Issue by BhargavRentala** [palmetto/Palmetto#340]
Starting 12/11/2019, Sunlight Financial will make the below attributes available for you to supply Sales
Representative information when making calls via API. Doing so will allow your representatives to
participate in Sunlight’s Rewards program. Additionally, when providing the Sales Representative’s email
address, project notifications will be sent here, too. This change is voluntary, but we highly recommend
making this change.
All attributes are provided at the Projects level

**Comment by BhargavRentala** [comment]
![image.png](https://images.zenhubusercontent.com/5db873bb0f0394000100138b/238abf43-36c6-412c-af21-95b0ade87407)

**Comment by leonardotreeline** [comment]
@BhargavRentala 
Estimate 3
Starting work on it

**Comment by leonardotreeline** [comment]
@BhargavRentala 
Prequal call data being sent 
"{"prequal":{"firstName":"Leonardo","lastName":"Noli","street":"328 W Morgan St","city":"Raleigh","stateName":"Florida","zipCode":"27601","annualIncome":"100000","isCreditAuthorized":true}}"
URL: "https://test.connect.boomi.com/ws/rest/v1/pt/prequal/create"

**Comment by leonardotreeline** [comment]
This would be the the data being sent after adding the rep values
"{"prequal":{"firstName":"Leonardo","lastName":"Noli","street":"328 W Morgan St","city":"Raleigh","stateName":"North Carolina","zipCode":"27601","annualIncome":"123231","isCreditAuthorized":true,"salesRepresentativeFirstName":"Chase","salesRepresentativeLastName":"Holroyd","salesRepresentativeOrg":null,"salesRepresentativeEmail":"chase.holroyd@palmetto.com"}}"

**Comment by leonardotreeline** [comment]
Data being sent to sunlight on choose financing
"{"term":120,"apr":2.99,"loanAmount":12036,"paydownPercentage":26}"

**Comment by BhargavRentala** [comment]
Waiting for deployment on Thursday.
