### ISSUE TITLE
LP 20 year 2.99 Configuration 

### ISSUE THREAD

**Issue by BhargavRentala** [palmetto/Palmetto#373]
| Name | Email | Description | URL | Priority | WideSpread | StepstoReproduce |
|---|---|---|---|---|---|---|---|
| Patrick Sanda | patrick.sanda@gmail.com | Trello 313

Alchemy selecting LP 20 year 2.99 product, LP is receiving 20 year 3.99 option.  | https://na90.salesforce.com/0062L00000SWmCv | High | Yes | 1) Rep/HO select 20 year 2.99 option in Alchemy
2) Process credit
3) HO receives a loan email from LP for 3.99 APR. 
4) Alchemy still shows 2.99
5) We check LP and confirm 3.99 is sticking 
6) We then manually COP and change the loan within LP.  |

**Comment by leonardotreeline** [comment]
Hopefully it will take me the first estimate but there are still several things i am not familiar with

**Comment by leonardotreeline** [comment]
@BhargavRentala I need some clarification. I have been through the flow and it seems following the flow on your description at that point you would still see the 3.99, if you re-run the credit check is when it updates the application to use the new 3.99. Could you test this on that customer please?

**Comment by leonardotreeline** [comment]
@BhargavRentala do you think someone could re run Patrick Sanda's app? I updated my local database to match current production and I can't recreate the not updating to the 3.99 part. I did a screen share with @kellengarnaas to see if I was missing something of the process but it seems I am following the right process. The selected financing uption updates after the credit check has been re ran. This screenshot is from my local environment after choosing 2.99, 3.99 and 4.99 from loanpal and selecting 3.99 from those options

![Screen Shot 2020-01-31 at 3.34.55 PM.png](https://images.zenhubusercontent.com/5e28ee3b8cc526a7cc897af1/e0d535b3-5e21-48ea-80c7-0dc79db8e30e)

**Comment by BhargavRentala** [comment]
We are sending the right product. @BhargavRentala  to check if the error is on LP side

**Comment by BhargavRentala** [comment]
Its not an issue anymore per Donnie
