### ISSUE TITLE
Impact on SF fields removal

### ISSUE THREAD

**Issue by BhargavRentala** [palmetto/Palmetto#375]
is Home/alchemy going to break if the following salesforce fields are deleted?

1. NDA__c	
2. NDA_Signed_Received__c	
3. Background_Check_Completed_Received__c	
4. MSA_Signed_Received__c	
5. ACH_Direct_Deposit_Completed__c	
6. W_9_Completed_Received__c	
7. W9__c
8. Insurance_Signature__c
9. Insurance_Received__c
10. MSA__c
11. MSA_Received_Date__c
12. ACH__c
13. Onboarding_Form__c	
14. Insurance_Received__c

**Comment by kellengarnaas** [comment]
The only references to any of these values have been previously commented out in the codebase. No conflicts.

**Comment by BhargavRentala** [comment]
Thanks.
