### ISSUE TITLE
Error when editing opportunity for Charles Wilson

### ISSUE THREAD

**Issue by leonardotreeline** [palmetto/Palmetto#378]
Logged in as a design agent clicking to edit Charles Wilson's opportunity yields the following error![Screen Shot 2020-01-31 at 10.05.46 AM.png](https://images.zenhubusercontent.com/5e28ee3b8cc526a7cc897af1/b31b483e-3b40-47fe-ac78-348a9995079e)

**Comment by leonardotreeline** [comment]
@BhargavRentala the entry for Charles Wilson is breaking because it's using the opportunity_proposal_id 82530 which lacks "opportunity loan plan details" and "opportunity pricing details" the system's way to determine which proposal id to use is flawed it kind of seems it is supposed to pull the last encountered id no matter what but the results are not sorted in any specific way. 
How is the proposal selection supposed to happen to know what to edit?

**Comment by BhargavRentala** [comment]
Move these opportunities to Sales pipeline or something.
