### ISSUE TITLE
Vendor Management 

### ISSUE THREAD

**Issue by BhargavRentala** [palmetto/Palmetto#386]
| Name | Email | Description | URL | Priority | WideSpread | StepstoReproduce |
|---|---|---|---|---|---|---|---|
| Terry McComb | terry.mccomb@palmetto.com | Saleforce opportunity for onboarding new build partners  | https://docs.google.com/forms/d/e/1FAIpQLSdIojRsc8OeBQ27hbjnIcEU1WmanUkyN_nkJwKgG_7Kd3v_AA/viewform | Medium | Yes | Sending via email  |

**Comment by BhargavRentala** [comment]
[https://app.zenhub.com/files/218788768/1ab77d4c-3afa-4475-ab8b-d4528d3a2014/download](https://app.zenhub.com/files/218788768/1ab77d4c-3afa-4475-ab8b-d4528d3a2014/download)

**Comment by TyFrye** [comment]
https://drive.google.com/file/d/18bX7C__6Ev173NoTOnY7XtX3bWdShMHW/view?usp=sharing
